### ISSUE TITLE
Caching of lookups

### ISSUE THREAD

**Issue by chrisRidgers** [Kruithne/Recipe-Completion#6]
Might be deliberate, might not.  Might be cloudflare.

I stuck my toons details into the site yesterday and got stuff back, but I've done stuff since then and its not updated at all.  I've tried disabling my browser cache, using an icognito window etc, always comes back with the same results.

Is the refresh time locked to something like a weekly reset?  Im at nearly 24 hours now and not been able to get up to date results out of it.

**Comment by Kruithne** [comment]
The site has an internal cache of around 24-hours which is used to buffer from the Blizzard armory, shared with other tools running on the server, to prevent using up our API quota.

You should find your character data updates within 24-48 hours of when it last did. If the problem persists for a few days, and the armory is up-to-date, re-open the issue and I'll take a closer look.

**Comment by chrisRidgers** [comment]
Looks like I was just impatient, cheers for the response
